"""add_quick_access_item

Revision ID: 7f42b0a82d42
Revises: 058daad59c02
Create Date: 2026-07-13 14:55:50.167520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f42b0a82d42'
down_revision: Union[str, Sequence[str], None] = '058daad59c02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quick_access_item',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('abbr', sa.String(length=10), nullable=False),
    sa.Column('href', sa.String(length=500), nullable=False),
    sa.Column('bg_class', sa.String(length=100), nullable=False),
    sa.Column('text_class', sa.String(length=100), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('is_special', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quick_access_item')
    # ### end Alembic commands ###
