"""add_ldap_fields_and_ad_group_mapping

Revision ID: c5bba6d4f2a5
Revises: 67f992a85dda
Create Date: 2026-07-13 11:13:23.084125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5bba6d4f2a5'
down_revision: Union[str, Sequence[str], None] = '67f992a85dda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ad_group_mapping',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('ad_group_name', sa.String(length=255), nullable=False),
    sa.Column('ad_group_dn', sa.String(length=512), nullable=False),
    sa.Column('group_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id')
    )
    op.add_column('user', sa.Column('ad_username', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('ad_dn', sa.String(length=512), nullable=True))
    op.add_column('user', sa.Column('last_login', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint(None, 'user', ['ad_username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'last_login')
    op.drop_column('user', 'ad_dn')
    op.drop_column('user', 'ad_username')
    op.drop_table('ad_group_mapping')
    # ### end Alembic commands ###
